steps:
- name: 'gcr.io/cloud-builders/docker'
args: [
  'build',
  '-t',
  'us-central1-docker.pkg.dev/ganesh-sona-dev/github_ganeshsonawane06_web_app/web_app:latest',
  '.'
]
timeout: 36s
images: ['gcr.io/ganesh-sona-dev/web_app:latest']